head_rank:
  score: '%player_level%'
  nodes:
    - "0: &2新手"
    - "50: &a猎手"
    - "100: &d巫师"
    - "200: &7&l守卫"
    - "500: &3骑士"
    - "1000: &b勇士"
    - "1000: &e天使"
    - "5000: &f&l天子"
    - "10000: &b&l冠军"