settings:
  # Use the title instead for the title of the player outside the numerical range.
  # 对超出数值范围玩家的称号使用该称号代替.
  unknown-instead: '&7Unknown'

head_rank:
  # count
  # 数值
  score: '%player_level%'
  # Format: count: tag
  # 格式: 数值: 对应称号
  nodes:
    - "0: &2新手"
    - "50: &a猎手"
    - "100: &d巫师"
    - "200: &7&l守卫"
    - "500: &3骑士"
    - "1000: &b勇士"
    - "1000: &e天使"
    - "5000: &f&l天子"
    - "10000: &b&l冠军"